#!/usr/bin/env bash
# lib/report_html.sh — Standalone dark-themed HTML report
# Part of cisaudit — Linux CIS Hardening Auditor
#
# Generates a single self-contained HTML file with:
#   - Embedded CSS (dark theme + print stylesheet)
#   - <details>-based collapsible control list
#   - No external dependencies (no CDN, no fonts from internet)

# ── HTML entity escaping ──────────────────────────────────────────────────────
html_escape() {
  local s="$1"
  s="${s//&/&amp;}"
  s="${s//</&lt;}"
  s="${s//>/&gt;}"
  s="${s//\"/&quot;}"
  echo -n "$s"
}

# ── Score color class ─────────────────────────────────────────────────────────
score_class() {
  local score="$1"
  if awk -v s="$score" 'BEGIN { exit !(s >= 80) }'; then
    echo "score-good"
  elif awk -v s="$score" 'BEGIN { exit !(s >= 50) }'; then
    echo "score-warn"
  else
    echo "score-bad"
  fi
}

# ── Main entry point ──────────────────────────────────────────────────────────
emit_html_report() {
  local timestamp
  timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
  local host
  host="$(hostname 2>/dev/null || echo unknown)"
  local mode
  [[ "$SYSROOT" == "/" ]] && mode="Live System" || mode="Test Mode (${SYSROOT})"

  cat <<HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>cisaudit Report — $(html_escape "$host") — $timestamp</title>
  <meta name="description" content="CIS Hardening Audit Report for $(html_escape "$host") generated by cisaudit v${CISAUDIT_VERSION}">
  <style>
    /* ── Reset & Base ── */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    :root {
      --bg:       #0d1117;
      --bg2:      #161b22;
      --bg3:      #21262d;
      --border:   #30363d;
      --text:     #c9d1d9;
      --text-dim: #8b949e;
      --green:    #3fb950;
      --red:      #f85149;
      --yellow:   #d29922;
      --blue:     #58a6ff;
      --cyan:     #79c0ff;
      --purple:   #bc8cff;
      --font: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
      --mono: 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
    }
    body { background: var(--bg); color: var(--text); font-family: var(--font);
           font-size: 14px; line-height: 1.6; padding: 0 0 40px; }

    /* ── Header ── */
    header {
      background: linear-gradient(135deg, #0d1117 0%, #161b22 50%, #0d1117 100%);
      border-bottom: 1px solid var(--border);
      padding: 32px 40px 24px;
    }
    .logo { font-size: 28px; font-weight: 700; color: var(--cyan);
            display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
    .logo-icon { font-size: 36px; }
    .subtitle { color: var(--text-dim); font-size: 13px; }
    .meta-row { display: flex; gap: 24px; margin-top: 16px; flex-wrap: wrap; }
    .meta-item { background: var(--bg3); border: 1px solid var(--border);
                 border-radius: 6px; padding: 6px 14px; font-size: 12px;
                 color: var(--text-dim); }
    .meta-item strong { color: var(--text); }

    /* ── Main layout ── */
    main { max-width: 1100px; margin: 32px auto; padding: 0 40px; }

    /* ── Score card ── */
    .score-card {
      background: var(--bg2); border: 1px solid var(--border); border-radius: 12px;
      padding: 28px 32px; display: flex; align-items: center; gap: 40px;
      margin-bottom: 32px; flex-wrap: wrap;
    }
    .big-score { font-size: 64px; font-weight: 800; line-height: 1; }
    .score-good { color: var(--green); }
    .score-warn { color: var(--yellow); }
    .score-bad  { color: var(--red); }
    .score-label { color: var(--text-dim); font-size: 13px; margin-top: 4px; }
    .counters { display: flex; gap: 24px; flex-wrap: wrap; }
    .counter { text-align: center; }
    .counter .val { font-size: 32px; font-weight: 700; line-height: 1; }
    .counter .lbl { font-size: 11px; text-transform: uppercase;
                    letter-spacing: 0.08em; color: var(--text-dim); margin-top: 2px; }
    .pass-val  { color: var(--green); }
    .fail-val  { color: var(--red); }
    .warn-val  { color: var(--yellow); }
    .skip-val  { color: var(--text-dim); }

    /* ── Progress bar ── */
    .progress-bar { background: var(--bg3); border-radius: 4px; height: 8px;
                    overflow: hidden; flex: 1; min-width: 80px; }
    .progress-fill { height: 100%; border-radius: 4px; transition: width 0.3s; }
    .fill-good { background: linear-gradient(90deg, #238636, #3fb950); }
    .fill-warn { background: linear-gradient(90deg, #9e6a03, #d29922); }
    .fill-bad  { background: linear-gradient(90deg, #b91c1c, #f85149); }

    /* ── Section table ── */
    h2 { color: var(--text); font-size: 16px; font-weight: 600;
         margin: 32px 0 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
    th { text-align: left; color: var(--text-dim); font-weight: 500; font-size: 12px;
         text-transform: uppercase; letter-spacing: 0.06em;
         padding: 8px 12px; border-bottom: 1px solid var(--border); }
    td { padding: 10px 12px; border-bottom: 1px solid var(--border); vertical-align: middle; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: var(--bg3); }
    .section-progress { display: flex; align-items: center; gap: 10px; min-width: 140px; }
    .section-pct { font-weight: 600; min-width: 42px; }

    /* ── Control list ── */
    .controls-section { margin-bottom: 32px; }
    .section-header {
      background: var(--bg3); border: 1px solid var(--border); border-radius: 8px 8px 0 0;
      padding: 12px 18px; display: flex; align-items: center; gap: 12px;
      font-weight: 600; color: var(--cyan); font-size: 14px;
    }
    .section-count { background: var(--bg); border: 1px solid var(--border);
                     border-radius: 20px; padding: 2px 10px; font-size: 11px;
                     color: var(--text-dim); margin-left: auto; }
    details { border: 1px solid var(--border); border-top: none; }
    details:last-child { border-radius: 0 0 8px 8px; }
    summary {
      padding: 10px 18px; cursor: pointer; display: flex; align-items: center; gap: 12px;
      user-select: none; list-style: none;
    }
    summary::-webkit-details-marker { display: none; }
    summary:hover { background: var(--bg3); }
    details[open] summary { background: var(--bg3); border-bottom: 1px solid var(--border); }
    .ctrl-id { font-family: var(--mono); font-size: 12px;
               color: var(--text-dim); min-width: 60px; }
    .ctrl-level { background: var(--bg3); border: 1px solid var(--border);
                  border-radius: 4px; padding: 1px 6px; font-size: 11px;
                  color: var(--purple); min-width: 24px; text-align: center; }
    .ctrl-title { flex: 1; }
    .badge {
      padding: 2px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;
      text-transform: uppercase; letter-spacing: 0.06em; min-width: 46px;
      text-align: center;
    }
    .badge-PASS { background: #1a3a20; color: var(--green); border: 1px solid #2a5030; }
    .badge-FAIL { background: #3a1a1a; color: var(--red);   border: 1px solid #5a2020; }
    .badge-WARN { background: #3a2e00; color: var(--yellow); border: 1px solid #5a4a00; }
    .badge-SKIP { background: var(--bg3); color: var(--text-dim); border: 1px solid var(--border); }
    .ctrl-detail { padding: 14px 18px 14px 48px; font-size: 13px; }
    .detail-row { margin-bottom: 8px; }
    .detail-label { color: var(--text-dim); font-size: 11px; text-transform: uppercase;
                    letter-spacing: 0.06em; margin-bottom: 2px; }
    .detail-value { font-family: var(--mono); background: var(--bg);
                    border: 1px solid var(--border); border-radius: 4px;
                    padding: 6px 12px; color: var(--text); font-size: 12px;
                    white-space: pre-wrap; word-break: break-all; }
    .detail-value.remediation { color: var(--yellow); }
    details[open]:has(.badge-FAIL) { border-left: 3px solid var(--red); }
    details[open]:has(.badge-PASS) { border-left: 3px solid var(--green); }
    details[open]:has(.badge-WARN) { border-left: 3px solid var(--yellow); }

    /* ── Footer ── */
    footer { max-width: 1100px; margin: 0 auto; padding: 24px 40px 0;
             border-top: 1px solid var(--border); color: var(--text-dim); font-size: 12px; }

    /* ── Print ── */
    @media print {
      body { background: #fff; color: #000; }
      header { background: #f5f5f5; border-bottom: 2px solid #000; }
      .logo { color: #000; }
      .big-score.score-good { color: #1a7a2a; }
      .big-score.score-bad  { color: #b00; }
      details { border: 1px solid #ccc; }
      details[open] { page-break-inside: avoid; }
    }
  </style>
</head>
<body>

<header>
  <div class="logo"><span class="logo-icon">🔒</span> Linux CIS Hardening Auditor</div>
  <div class="subtitle">$(html_escape "$BENCHMARK_ID")</div>
  <div class="meta-row">
    <div class="meta-item"><strong>Host:</strong> $(html_escape "$host")</div>
    <div class="meta-item"><strong>Mode:</strong> $(html_escape "$mode")</div>
    <div class="meta-item"><strong>Generated:</strong> $timestamp</div>
    <div class="meta-item"><strong>Version:</strong> cisaudit v$(html_escape "$CISAUDIT_VERSION")</div>
  </div>
</header>

<main>

  <!-- Score Card -->
  <div class="score-card">
    <div>
      <div class="big-score $(score_class "$SCORE_OVERALL")">${SCORE_OVERALL}%</div>
      <div class="score-label">Overall Compliance Score</div>
    </div>
    <div class="counters">
      <div class="counter"><div class="val pass-val">${TOTAL_PASS}</div><div class="lbl">Pass</div></div>
      <div class="counter"><div class="val fail-val">${TOTAL_FAIL}</div><div class="lbl">Fail</div></div>
      <div class="counter"><div class="val warn-val">${TOTAL_WARN}</div><div class="lbl">Warn</div></div>
      <div class="counter"><div class="val skip-val">${TOTAL_SKIP}</div><div class="lbl">Skip</div></div>
      <div class="counter"><div class="val">${TOTAL_CONTROLS}</div><div class="lbl">Total</div></div>
    </div>
  </div>

  <!-- Section Scores Table -->
  <h2>Section Scores</h2>
  <table>
    <thead>
      <tr>
        <th>Section</th>
        <th>Score</th>
        <th>Pass</th>
        <th>Fail</th>
        <th>Warn</th>
        <th>Skip</th>
        <th style="min-width:160px">Progress</th>
      </tr>
    </thead>
    <tbody>
HTMLEOF

  for section in "${SECTIONS[@]}"; do
    local total="${SECTION_TOTAL[$section]:-0}"
    (( total > 0 )) || continue
    local score="${SECTION_SCORE[$section]:-0.0}"
    local sp="${SECTION_PASS[$section]:-0}"
    local sf="${SECTION_FAIL[$section]:-0}"
    local sw="${SECTION_WARN[$section]:-0}"
    local sk="${SECTION_SKIP[$section]:-0}"
    local name
    name="$(html_escape "${SECTION_NAMES[$section]:-$section}")"
    local cls
    cls="$(score_class "$score")"
    local fill_cls
    case "$cls" in
      score-good) fill_cls="fill-good" ;;
      score-warn) fill_cls="fill-warn" ;;
      *)          fill_cls="fill-bad"  ;;
    esac

    cat <<ROWEOF
      <tr>
        <td>$name</td>
        <td class="$cls" style="font-weight:600">${score}%</td>
        <td style="color:var(--green)">$sp</td>
        <td style="color:var(--red)">$sf</td>
        <td style="color:var(--yellow)">$sw</td>
        <td style="color:var(--text-dim)">$sk</td>
        <td>
          <div class="section-progress">
            <div class="progress-bar">
              <div class="progress-fill $fill_cls" style="width:${score}%"></div>
            </div>
          </div>
        </td>
      </tr>
ROWEOF
  done

  cat <<HTMLEOF2
    </tbody>
  </table>

  <!-- Control Detail -->
  <h2>Control Results</h2>
HTMLEOF2

  local current_section=""
  for id in "${RESULT_ORDER[@]}"; do
    local section="${CTRL_SECTION[$id]}"
    local status="${RESULT_STATUS[$id]:-SKIP}"
    local title
    title="$(html_escape "${CTRL_TITLE[$id]}")"
    local level="${CTRL_LEVEL[$id]:-1}"
    local desc
    desc="$(html_escape "${CTRL_DESCRIPTION[$id]}")"
    local evidence
    evidence="$(html_escape "${RESULT_EVIDENCE[$id]}")"
    local fix
    fix="$(html_escape "${CTRL_REMEDIATION[$id]}")"

    if [[ "$section" != "$current_section" ]]; then
      # Close previous section
      [[ -n "$current_section" ]] && echo "</div>"
      current_section="$section"
      local sname
      sname="$(html_escape "${SECTION_NAMES[$section]:-$section}")"
      local st="${SECTION_TOTAL[$section]:-0}"
      echo "<div class=\"controls-section\">"
      echo "<div class=\"section-header\">📂 $sname <span class=\"section-count\">$st controls</span></div>"
    fi

    # Auto-open FAIL controls; collapse PASS
    local open_attr=""
    [[ "$status" == "FAIL" || "$status" == "WARN" ]] && open_attr=" open"

    echo "<details${open_attr}>"
    echo "  <summary>"
    echo "    <span class=\"ctrl-id\">$id</span>"
    echo "    <span class=\"ctrl-level\">L${level}</span>"
    echo "    <span class=\"ctrl-title\">$title</span>"
    echo "    <span class=\"badge badge-${status}\">${status}</span>"
    echo "  </summary>"
    echo "  <div class=\"ctrl-detail\">"
    if [[ -n "$desc" ]]; then
      echo "    <div class=\"detail-row\"><div class=\"detail-label\">Description</div>"
      echo "    <div class=\"detail-value\">$desc</div></div>"
    fi
    if [[ -n "$evidence" ]]; then
      echo "    <div class=\"detail-row\"><div class=\"detail-label\">Evidence</div>"
      echo "    <div class=\"detail-value\">$evidence</div></div>"
    fi
    if [[ -n "$fix" && ( "$status" == "FAIL" || "$status" == "WARN" ) ]]; then
      echo "    <div class=\"detail-row\"><div class=\"detail-label\">Remediation</div>"
      echo "    <div class=\"detail-value remediation\">$fix</div></div>"
    fi
    echo "  </div>"
    echo "</details>"
  done

  [[ -n "$current_section" ]] && echo "</div>"

  cat <<FOOTEREOF

</main>

<footer>
  <p>cisaudit v${CISAUDIT_VERSION} &nbsp;|&nbsp; $(html_escape "$BENCHMARK_ID") &nbsp;|&nbsp;
     Generated $timestamp on $(html_escape "$host")</p>
  <p style="margin-top:8px">
    ⚠️ Passing all controls does not mean the system is unbreakable.
    CIS hardening reduces attack surface and blast radius; defense-in-depth is still required.
  </p>
</footer>

</body>
</html>
FOOTEREOF
}
