#!/usr/bin/env bash
# install.sh — cisaudit One-Command Installer
# Part of cisaudit — Linux CIS Hardening Auditor
#
# Usage:
#   sudo bash install.sh          Install system-wide to /usr/local/bin/cisaudit
#   bash install.sh --user        Install to ~/bin/cisaudit (no sudo required)
#   bash install.sh --uninstall   Remove cisaudit

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY_NAME="cisaudit"
USER_INSTALL=0

# ── Color ─────────────────────────────────────────────────────────────────────
GREEN="\033[0;32m"; RED="\033[0;31m"; YELLOW="\033[0;33m"
BOLD="\033[1m"; RESET="\033[0m"

log()  { echo -e "${GREEN}${BOLD}[install]${RESET} $*"; }
warn() { echo -e "${YELLOW}${BOLD}[warn]${RESET} $*"; }
err()  { echo -e "${RED}${BOLD}[error]${RESET} $*" >&2; }

# ── Parse args ────────────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --user)      USER_INSTALL=1; INSTALL_DIR="$HOME/bin" ;;
    --uninstall) UNINSTALL=1 ;;
    *) err "Unknown argument: $arg"; exit 1 ;;
  esac
done

# ── Bash version check ────────────────────────────────────────────────────────
log "Checking Bash version..."
if (( BASH_VERSINFO[0] < 4 )); then
  err "cisaudit requires Bash 4+. You have: $BASH_VERSION"
  warn "On macOS, install via Homebrew: brew install bash"
  exit 1
fi
log "Bash $BASH_VERSION ✓"

# ── Uninstall path ────────────────────────────────────────────────────────────
if [[ "${UNINSTALL:-0}" == "1" ]]; then
  local_bin="${INSTALL_DIR}/${BINARY_NAME}"
  if [[ -f "$local_bin" ]]; then
    rm -f "$local_bin"
    log "Removed $local_bin"
  else
    warn "cisaudit not found at $local_bin"
  fi
  exit 0
fi

# ── Root check (system install) ───────────────────────────────────────────────
if [[ "$USER_INSTALL" == "0" && "$(id -u)" != "0" ]]; then
  err "System-wide install requires root. Run: sudo bash install.sh"
  warn "Or install for current user only: bash install.sh --user"
  exit 1
fi

# ── Create install dir if needed ──────────────────────────────────────────────
if [[ ! -d "$INSTALL_DIR" ]]; then
  mkdir -p "$INSTALL_DIR"
  log "Created directory: $INSTALL_DIR"
fi

# ── Create wrapper script ─────────────────────────────────────────────────────
log "Installing cisaudit to ${INSTALL_DIR}/${BINARY_NAME}..."

cat > "${INSTALL_DIR}/${BINARY_NAME}" <<WRAPPER
#!/usr/bin/env bash
# cisaudit wrapper — generated by install.sh
exec bash "${SCRIPT_DIR}/cisaudit.sh" "\$@"
WRAPPER

chmod +x "${INSTALL_DIR}/${BINARY_NAME}"

log "Installation complete!"
echo ""
echo -e "  Run:  ${BOLD}cisaudit --help${RESET}"
echo -e "  Demo: ${BOLD}cisaudit -t ${SCRIPT_DIR}/testdata/fixtures${RESET}"
echo -e "  Live: ${BOLD}sudo cisaudit${RESET}"
echo ""

# ── PATH hint ─────────────────────────────────────────────────────────────────
if ! echo ":${PATH}:" | grep -q ":${INSTALL_DIR}:"; then
  warn "Note: ${INSTALL_DIR} is not in your PATH."
  warn "Add this to your ~/.bashrc or ~/.zshrc:"
  echo "  export PATH=\"\$PATH:${INSTALL_DIR}\""
fi
